ROLE_PERMISSIONS = {
    "superadmin": [
        "manage_users",
        "manage_roles",
        "manage_projects",
        "create_analysis",
        "edit_artifacts",
        "approve_requirements",
        "view_artifacts",
        "create_teams",
        "view_teams",
        "edit_teams",
        "archive_projects",
        "archive_teams",
        "restore_archives",
        "manage_access",
        "create_roles",
        "manage_password_policy",
        "manage_identity_providers",
        "manage_team_members",
        "assign_project_teams",
        "view_all_projects",
        "manage_tenants",
    ],
    "admin": [
        "manage_projects",
        "create_analysis",
        "edit_artifacts",
        "approve_requirements",
        "view_artifacts",
        "create_teams",
        "view_teams",
        "edit_teams",
        "archive_projects",
        "archive_teams",
        "create_roles",
        "manage_password_policy",
        "manage_identity_providers",
        "manage_team_members",
        "assign_project_teams",
        "view_all_projects",
    ],
    "business_analyst": [
        "create_analysis",
        "edit_artifacts",
        "approve_requirements",
        "view_artifacts",
        "create_teams",
        "view_teams",
        "edit_teams",
        "manage_team_members",
        "assign_project_teams",
    ],
    "viewer": ["view_artifacts", "view_teams"],
}

ROLE_DESCRIPTIONS = {
    "superadmin": "Unrestricted platform administration and governance.",
    "admin": "Workspace, project, team, and delivery administration.",
    "business_analyst": "Creates and maintains business analysis artifacts.",
    "viewer": "Read-only access to authorized teams and artifacts.",
}
