"""add restored_at to artifact versions

Revision ID: 09f87abf9cf4
Revises: 99ef31aa339d
Create Date: 2026-05-26 16:47:47.222126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f87abf9cf4'
down_revision: Union[str, Sequence[str], None] = '99ef31aa339d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_analysis_artifacts_current_version_id'), 'analysis_artifacts', ['current_version_id'], unique=False)
    op.add_column('artifact_versions', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artifact_versions_current_version_id'), 'artifact_versions', ['current_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_versions_current_version_id'), table_name='artifact_versions')
    op.drop_column('artifact_versions', 'current_version_id')
    op.drop_index(op.f('ix_analysis_artifacts_current_version_id'), table_name='analysis_artifacts')
    op.drop_column('analysis_artifacts', 'current_version_id')
    # ### end Alembic commands ###
