"""add restored_at to artifact versions

Revision ID: 216eb4aa9b92
Revises: 09f87abf9cf4
Create Date: 2026-05-26 16:54:50.558733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216eb4aa9b92'
down_revision: Union[str, Sequence[str], None] = '09f87abf9cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
