"""add selected techniques context

Revision ID: 41be02a60b56
Revises: 63d2d5ba15fe
Create Date: 2026-05-27 03:57:57.862416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41be02a60b56'
down_revision: Union[str, Sequence[str], None] = '63d2d5ba15fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('selected_techniques', sa.JSON(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('infer_additional_techniques', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_artifacts', 'infer_additional_techniques')
    op.drop_column('analysis_artifacts', 'selected_techniques')
    # ### end Alembic commands ###
