"""add analysis domain field

Revision ID: 54ab7037cf52
Revises: bc453b501388
Create Date: 2026-05-26 18:09:55.995919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ab7037cf52'
down_revision: Union[str, Sequence[str], None] = 'bc453b501388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_artifacts', 'domain')
    # ### end Alembic commands ###
