"""add analysis activity context fields

Revision ID: 63d2d5ba15fe
Revises: ddc81144f277
Create Date: 2026-05-27 03:40:21.161584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d2d5ba15fe'
down_revision: Union[str, Sequence[str], None] = 'ddc81144f277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('selected_activity_keys', sa.JSON(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('selected_activity_labels', sa.JSON(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('selected_outputs', sa.JSON(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('source_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_artifacts', 'source_files')
    op.drop_column('analysis_artifacts', 'selected_outputs')
    op.drop_column('analysis_artifacts', 'selected_activity_labels')
    op.drop_column('analysis_artifacts', 'selected_activity_keys')
    # ### end Alembic commands ###
