"""add restored_at to artifact versions

Revision ID: 99ef31aa339d
Revises: 
Create Date: 2026-05-26 15:31:19.138382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ef31aa339d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_versions', sa.Column('version_type', sa.String(), nullable=True))
    op.add_column('artifact_versions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('artifact_versions', sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_artifact_versions_created_at'), 'artifact_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifact_versions_is_active'), 'artifact_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_artifact_versions_restored_at'), 'artifact_versions', ['restored_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_versions_restored_at'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_is_active'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_created_at'), table_name='artifact_versions')
    op.drop_column('artifact_versions', 'restored_at')
    op.drop_column('artifact_versions', 'is_active')
    op.drop_column('artifact_versions', 'version_type')
    # ### end Alembic commands ###
