"""add project context fields

Revision ID: bc453b501388
Revises: 216eb4aa9b92
Create Date: 2026-05-26 17:57:31.822678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc453b501388'
down_revision: Union[str, Sequence[str], None] = '216eb4aa9b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('project_type', sa.String(), server_default='internal', nullable=False))
    op.add_column('analysis_artifacts', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_artifacts', 'country')
    op.drop_column('analysis_artifacts', 'industry')
    op.drop_column('analysis_artifacts', 'company_name')
    op.drop_column('analysis_artifacts', 'project_type')
    # ### end Alembic commands ###
