"""add analysis focus fields

Revision ID: ddc81144f277
Revises: 54ab7037cf52
Create Date: 2026-05-26 18:16:50.103486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc81144f277'
down_revision: Union[str, Sequence[str], None] = '54ab7037cf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_artifacts', sa.Column('analysis_focus_key', sa.String(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('analysis_focus_chapter', sa.String(), nullable=True))
    op.add_column('analysis_artifacts', sa.Column('analysis_focus_area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_artifacts', 'analysis_focus_area')
    op.drop_column('analysis_artifacts', 'analysis_focus_chapter')
    op.drop_column('analysis_artifacts', 'analysis_focus_key')
    # ### end Alembic commands ###
